"""Generate GPT-based natural language intents for the single-target benchmark.

Usage:
    python -m spacefit_v2.scripts.generate_gpt_intents \
        --benchmark_dir spacefit_v2/data/single_target_benchmark \
        --split test \
        --model gpt-4o \
        --out spacefit_v2/data/single_target_benchmark/gpt_intent_cases_test.json
"""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path

from spacefit_v2.single_target.gpt_intent_gen import generate_gpt_intents_for_cases


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description="Generate GPT intents for benchmark cases")
    p.add_argument("--benchmark_dir", default="spacefit_v2/data/single_target_benchmark")
    p.add_argument("--split", default="test", help="Which split to process (train/val/test/all)")
    p.add_argument("--max_cases", type=int, default=None)
    p.add_argument("--model", default="gpt-4o")
    p.add_argument("--openai_api_key", default=None)
    p.add_argument("--openai_base_url", default=None,
                   help="Optional OpenAI-compatible base URL, e.g. DashScope, vLLM, or Ollama.")
    p.add_argument("--out", default=None,
                   help="Output path. Defaults to <benchmark_dir>/gpt_intent_cases_<split>.json")
    return p


def main(args: argparse.Namespace) -> None:
    benchmark_dir = Path(args.benchmark_dir)
    with open(benchmark_dir / "cases.json") as f:
        cases = json.load(f)

    split = args.split if args.split != "all" else None
    if split:
        targets = [c for c in cases if c["split"] == split]
    else:
        targets = list(cases)

    if args.max_cases:
        targets = targets[: args.max_cases]

    print(f"Generating GPT intents for {len(targets)} cases (split={args.split}, model={args.model})")

    api_key = args.openai_api_key or os.environ.get("OPENAI_API_KEY")
    if not api_key:
        raise SystemExit("ERROR: No OpenAI API key. Set OPENAI_API_KEY or pass --openai_api_key.")

    from openai import OpenAI
    kwargs = {"api_key": api_key}
    base_url = args.openai_base_url or os.environ.get("OPENAI_BASE_URL")
    if base_url:
        kwargs["base_url"] = base_url
    client = OpenAI(**kwargs)

    augmented = generate_gpt_intents_for_cases(
        targets, openai_client=client, model=args.model, split=None, verbose=True
    )

    out_path = args.out or str(benchmark_dir / f"gpt_intent_cases_{args.split}.json")
    with open(out_path, "w") as f:
        json.dump(augmented, f, indent=2)

    ok = sum(1 for c in augmented if c["gpt_intent"].get("model") != "fallback")
    print(f"\nDone: {ok}/{len(augmented)} generated by GPT, {len(augmented) - ok} fallbacks")
    print(f"Saved → {out_path}")


if __name__ == "__main__":
    main(build_parser().parse_args())
